import { AuthStrategyFactory, MagnetModule } from '@magnet/core'
import { Module } from '@nestjs/common'
import { ConfigModule } from '@nestjs/config'
import { MockAuthStrategy } from './strategies/mock-auth.strategy'

/**
 * Register the custom MockAuthStrategy before module initialization.
 *
 * This is how developers can add their own authentication strategies:
 * 1. Create a class that implements AuthStrategy
 * 2. Register it with AuthStrategyFactory.registerStrategy()
 * 3. Configure MagnetModule to use the strategy via auth.strategy option
 */
AuthStrategyFactory.registerStrategy('mock', MockAuthStrategy)

@Module({
	imports: [
		ConfigModule.forRoot({ isGlobal: true }),
		MagnetModule.forRoot({
			db: {
				uri:
					process.env.MONGODB_URI || 'mongodb://localhost:27017/auth-example',
			},
			jwt: {
				secret: process.env.JWT_SECRET || 'development-secret-key',
			},
			// Use the custom mock auth strategy
			auth: {
				strategy: 'mock',
				// IMPORTANT: Pass jwt config so custom strategy uses the same secret as Passport
				// This ensures tokens generated by the strategy can be verified by JwtAuthGuard
				jwt: {
					secret: process.env.JWT_SECRET || 'development-secret-key',
					expiresIn: '24h',
				},
			},
		}),
	],
})
export class AppModule {}
